[features]
seeds = false
skip-lint = false
[programs.devnet]
crouton_jones_nft_solana = "3Bj1KmAeobZ2rBg1GiitVXxoV6Z3zQZtCtYHTgCbUrcj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yudiz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
